export enum GENERAL_CODES {
  NOT_FOUND = "GRL.NOT_FOUND",
  INTERNAL = "GRL.INTERNAL",
  BAD_REQUEST = "GRL.BAD_REQUEST",
  VALIDATION = "GRL.VALIDATION",
  CONFLICT = "GRL.CONFLICT",
  UNAUTHORIZED = "GRL.UNAUTHORIZED",
  PRODUCT_CREATION_FAILED = "PRODUCT.FAILED"
}
