export enum GENERAL_CODES {
  NOT_FOUND = 'GRL.NOT_FOUND',
  INTERNAL = 'GRL.INTERNAL',
  BAD_REQUEST = 'GRL.BAD_REQUEST',
  VALIDATION = 'GRL.VALIDATION',
  CONFLICT = 'GRL.CONFLICT',
  UNAUTHORIZED = 'GRL.UNAUTHORIZED',
  PRODUCT_CREATION_FAILED = 'PRODUCT.FAILED',
  ORDER_CREATION_FAILED = 'ORDER.FAILED',
  OUT_OF_STUCK = 'PRODUCT.OUT_OF_STUCK',
  USER_NOT_FOUND = 'USER.NOT_FOUND',
  PRODUCT_NOT_FOUND = 'PRODUCT.NOT_FOUND',
}
